var nameList = [
    'Ace', 'Beau', 'Blake', 'Bliss', 'Cash', 'Cleo', 'Dash', 'Duke',
    'Elle', 'Finn', 'Gale', 'Hale', 'Jade', 'Jax', 'Kai', 'Kane', 
    'Knox', 'Leo', 'Luna', 'Mae', 'Max', 'Nash', 'Nova', 'Oak', 
    'Pax', 'Quinn', 'Reed', 'Rex', 'Rory', 'Rose', 'Sage', 'Sky', 
    'Tate', 'Vera', 'Wren', 'Zane', 'Zoe', 'Ash', 'Beck', 'Bly', 
    'Cade', 'Dax', 'Elle', 'Finn', 'Grey', 'Hope', 'Ivy', 'Jace',
    'Jett', 'Kade', 'Lux', 'Mia', 'Nico', 'Noah', 'Owen', 'Pia', 
    'Reed', 'Roe', 'Ruby', 'Sam', 'Sol', 'Tess', 'Trey', 'Vale', 
    'Wynn', 'Zed', 'Axel', 'Bryce', 'Cruz', 'Drew', 'Eve', 'Faye',
    'Gage', 'Hugh', 'Jude', 'Kirk', 'Leah', 'Milo', 'Nell', 'Odin', 
    'Poe', 'Rhea', 'Seth', 'Tara', 'Vera', 'Will', 'Xavi', 'Yara', 
    'Zara', 'Ari', 'Ben', 'Chad', 'Dean', 'Eli', 'Finn', 'Gus', 
    'Hank', 'Ike', 'Jill', 'Kira', 'Lane', 'Maeve', 'Ned', 'Omar',
    'Pete', 'Quinn', 'Rae', 'Sean', 'Tia', 'Vince', 'Walt', 'Xena',
    'Yuri', 'Zion'
  ];
  
export function generateRandomName() {
  return nameList[Math.floor(Math.random() * nameList.length)];
};





      var quoteList = [
        'Bitcoin is the future of money.',
        'Blockchain is the new internet.',
        'Invest in digital gold.',
        'Decentralize everything.',
        'Crypto is the new cash.',
        'HODL your crypto.',
        'Buy the dip.',
        'Ethereum powers decentralized apps.',
        'Altcoins are the future.',
        'Crypto is freedom.',
        'Adopt blockchain technology.',
        'Invest in innovation.',
        'Crypto is borderless.',
        'DeFi is the future of finance.',
        'Digital assets are here to stay.',
        'Crypto is the next internet.',
        'Blockchain is transparent.',
        'Embrace digital currencies.',
        'Crypto is the future.',
        'Decentralized finance for all.',
        'Cryptocurrencies are the new gold.',
        'Smart contracts are the future.',
        'Blockchain technology is revolutionary.',
        'Crypto is a global phenomenon.',
        'Invest in blockchain innovation.',
        'Crypto will change the world.',
        'Digital currencies are the new norm.',
        'Decentralization is the key.',
        'Blockchain is the backbone of the future.',
        'Crypto is a game-changer.',
        'Blockchain will transform industries.',
        'Invest in the future of money.',
        'Crypto is unstoppable.',
        'Blockchain is secure and transparent.',
        'Digital assets are the future.',
        'Embrace the crypto revolution.',
        'Crypto is the new digital economy.',
        'Blockchain for a better world.',
        'Cryptocurrencies are the future of finance.',
        'Invest in decentralized technology.',
        'Crypto is the future of transactions.',
        'Blockchain is tamper-proof.',
        'Crypto is the next big thing.',
        'Blockchain technology is the future.',
        'Digital currencies are secure.',
        'Decentralize and democratize finance.',
        'Crypto is the future of wealth.',
        'Blockchain ensures transparency.',
        'Crypto is a revolutionary technology.',
        'Invest in the crypto ecosystem.',
        'Blockchain will disrupt industries.',
        'Digital assets are the next evolution.',
        'Embrace the future with crypto.',
        'Crypto is a digital revolution.',
        'Blockchain is the technology of trust.',
        'Crypto is the future of payments.',
        'Invest in the digital gold rush.',
        'Crypto is reshaping finance.',
        'Blockchain for a decentralized world.',
        'Cryptocurrencies are here to stay.',
        'Invest in the blockchain revolution.',
        'Crypto is the future of commerce.',
        'Blockchain enables trustless transactions.',
        'Digital currencies are the new reality.',
        'Decentralize finance with crypto.',
        'Crypto is transforming the financial system.',
        'Blockchain is the future of security.',
        'Crypto is the new frontier of money.',
        'Invest in blockchain startups.',
        'Crypto is the digital currency of the future.',
        'Blockchain is the new financial infrastructure.',
        'Digital assets for the digital age.',
        'Embrace the blockchain technology.',
        'Crypto is the evolution of money.',
        'Blockchain is the foundation of future finance.',
        'Cryptocurrencies are changing the world.',
        'Invest in the decentralized future.',
        'Crypto is the future of trading.',
        'Blockchain brings transparency to finance.',
        'Crypto is the new financial paradigm.',
        'Blockchain is revolutionizing industries.',
        'Digital currencies are the future of payments.',
        'Decentralize your wealth with crypto.',
        'Crypto is the new age of finance.',
        'Blockchain is the key to a decentralized future.',
        'Crypto is the future of investing.',
        'Invest in the technology of the future.',
        'Crypto is the financial system of tomorrow.',
        'Blockchain is the new digital ledger.',
        'Digital assets are transforming finance.',
        'Embrace the crypto future.',
        'Crypto is redefining money.',
        'Blockchain is the future of ownership.',
        'Crypto is the new global currency.',
        'Blockchain technology for a better future.',
        'Cryptocurrencies are the future of wealth.',
        'Invest in the blockchain economy.',
        'Crypto is the digital future of money.'
      ];
    
    export function generateRandomQuote() {
      return quoteList[Math.floor(Math.random() * quoteList.length)];
    };
    